Feature:
  <Some interesting description here>

  Scenario:
    Given Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given 1Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given 2Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given 3Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given 4Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given 5Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given 6Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given D7o you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given 8Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given 9Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given 0Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given -Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given =Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given qDo you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given wDo you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given eDo you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given rDo you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given Dto you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given Dyo you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given Dou you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given Do iyou want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given Do yoou want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given Do yopu want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given Do youa want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given Do you awant to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given Do you waant to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
Given Do you waant to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.Do you want to discuss this issue? Connect to HipChat.
